use_frameworks!
platform :ios, '11.0'

# plugin 'cocoapods-art', :sources => [
#   'cocoapods-cocoapods',
#   'NFMC.cocoapods.Release'
# ]

target 'SwiftBank_Example' do
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftBank', :path => '../'

  target 'SwiftBank_Tests' do
    inherit! :search_paths

    
  end
end
